### ISSUE TITLE
Hosting the project on LuaRocks

### ISSUE THREAD

**Issue by firoxer** [codeplea/minctest-lua#1]
I noticed that the project can't be found in LuaRocks. I think there would be many benefits for uploading it there. At least the audience could/would be bigger.

As far as I know, there would be only three steps:
1. Adding a rockspec
2. Creating a LuaRocks account
3. Uploading the thing

I can create a barebones rockspec if it helps. I'm new to Lua and its ecosystem anyway so this would be a nice exercise to me, too.

**Comment by codeplea** [comment]
Thanks. I think this is a good idea. I'll look into it.

**Comment by codeplea** [comment]
Ok, I think I have this going.

Could you please try: `luarocks install minctest` and let me know how it works?

**Comment by firoxer** [comment]
Works just like it should. Thanks a lot :)

**Comment by codeplea** [comment]
Thanks for the feedback!
